grafana:
  service:
    type: LoadBalancer
    port: 80
prometheus:
  prometheusSpec:
    service:
      type: ClusterIP
      port: 9090
prometheus-node-exporter:
  enabled: true
  hostNetwork: true
  hostPID: true
  tolerations:
  - operator: "Exists"
  podSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
kube-state-metrics:
  enabled: true