apiVersion: v1
kind: Service
metadata:
  name: house-price-service
  namespace: default
spec:
  selector:
    app: house-price-api
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer  # GKE will assign an external IP