name: Build Image and Update Manifests for ArgoCD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    env:
      # Use your project details and desired image naming/versioning:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      # The base image path without a tag (adjust if needed)
      BASE_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app
      # Create a dynamic tag (e.g., v1.0.run_number)
      IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app:v1.0.${{ github.run_number }}
      # You may need these for later steps (like fetching GKE credentials) if you ever want to add them.
      CLUSTER: ${{ secrets.GKE_CLUSTER }}
      ZONE: ${{ secrets.GKE_ZONE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image with New Tag
        run: |
          echo "Building Docker image: $IMAGE"
          # Build the image using the Dockerfile in the app folder. 
          # Set the build context as the app folder.
          docker build -f app/Dockerfile -t $IMAGE app

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image: $IMAGE"
          docker push $IMAGE

      - name: Update Kubernetes Deployment Manifest
        run: |
          echo "Updating image in manifests/deployment.yaml to: $IMAGE"
          # Replace the existing image reference with the new image.
          # This command expects that your manifest contains a line with the base image and an existing tag.
          sed -i "s|${BASE_IMAGE}:[^ ]*|${IMAGE}|g" manifests/deployment.yaml
          echo "Updated deployment manifest:"
          cat manifests/deployment.yaml

      - name: Commit and Push Updated Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Check if there are changes in the manifest
          if [ -n "$(git status --porcelain manifests/deployment.yaml)" ]; then
              echo "Changes detected in manifests/deployment.yaml; committing..."
              git add manifests/deployment.yaml
              git commit -m "Update deployment image to ${IMAGE}"
              git push
          else
              echo "No changes detected in manifests/deployment.yaml."
          fi
