name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # The Google Cloud project ID where your Artifact Registry is located
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      # Full path to your Docker image, including the repository name and image name.
      # e.g. us-central1-docker.pkg.dev/<PROJECT_ID>/ml-housing-repo/ml-housing-app
      BASE_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app
      # Tag the image dynamically using the GitHub run number (e.g., v1.0.12)
      IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app:v1.0.${{ github.run_number }}

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          echo "Building Docker image: $IMAGE"
          docker build -f app/Dockerfile -t $IMAGE app
