name: CI/CD Pipeline for ML Model Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # Use your project details:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      # The full image path (static tag "v1.1")
      IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app:v1.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Repository Files (Debug)
        run: |
          echo "Repository structure:"
          ls -R $GITHUB_WORKSPACE

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: |
          # Configure Docker to authenticate with your Artifact Registry in us-central1
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        working-directory: app
        run: |
          echo "Building Docker image: $IMAGE"
          # Build the image using the Dockerfile in the "app" folder with "app" as context.
          docker build -t $IMAGE .

      - name: Push Docker Image to Artifact Registry
        run: |
          echo "Pushing Docker image: $IMAGE"
          docker push $IMAGE
