name: Build Image and Update Manifests for ArgoCD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    env:
      # Your Google Cloud project ID (e.g., "recoai-455707")
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      # Base image path without a tag.
      BASE_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app
      # Build a new image tag dynamically (example: v1.0.10)
      IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-housing-repo/ml-housing-app:v1.0.${{ github.run_number }}
      # These are available if you need them later (but are not used to deploy directly)
      CLUSTER: ${{ secrets.GKE_CLUSTER }}
      ZONE: ${{ secrets.GKE_ZONE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image with New Tag
        run: |
          echo "Building Docker image: $IMAGE"
          # Build the image using the Dockerfile in the "app" folder.
          docker build -f app/Dockerfile -t $IMAGE app

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image: $IMAGE"
          docker push $IMAGE

      - name: Update Kubernetes Deployment Manifest
        run: |
          echo "Updating image in manifests/deployment.yaml to: $IMAGE"
          # Replace the image reference in the deployment manifest.
          # This assumes that the manifest contains a line with the old image formatted as BASE_IMAGE:<tag>.
          sed -i "s|${BASE_IMAGE}:[^ ]*|${IMAGE}|g" manifests/deployment.yaml
          echo "Updated deployment manifest:"
          cat manifests/deployment.yaml

      - name: Commit and Push Updated Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain manifests/deployment.yaml)" ]; then
              echo "Changes detected in manifests/deployment.yaml; committing..."
              git add manifests/deployment.yaml
              git commit -m "Update deployment image to ${IMAGE}"
              git push
          else
              echo "No changes detected in manifests/deployment.yaml."
          fi
