name: Retrain Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies Forcing NumPy < 2
        run: |
          # Upgrade pip
          pip install --upgrade pip
          # Install a specific NumPy version that is compatible with your modules.
          pip install numpy==1.24.3
          
          # If you have a requirements.txt file, install it (adjust the path if needed)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f app/requirements.txt ]; then
            pip install -r app/requirements.txt
          fi
          
          # Install additional packages used by your training code.
          pip install pandas scikit-learn seaborn matplotlib scipy joblib psycopg2 sqlalchemy
          
          # Force-reinstall NumPy to ensure it isn’t overridden by any dependency.
          pip install numpy==1.24.3 --force-reinstall
          
          # Print out the installed NumPy version for confirmation.
          python -c "import numpy; print('NumPy version:', numpy.__version__)"

      - name: Remove Old Model File
        run: |
          if [ -f model/model.pkl ]; then
            echo "Removing old model at model/model.pkl..."
            rm model/model.pkl
          else
            echo "No old model file found in model/ folder."
          fi

      - name: Retrain the Model
        run: |
          # Run main.py with the 'retrain' argument so it only executes the training code.
          python app/main.py retrain

      - name: Move New Model File to model/ Folder
        run: |
          # If the training code outputs the file as model.pkl in the repository root,
          # then move it into the model directory.
          if [ -f model.pkl ]; then
            mkdir -p model
            mv model.pkl model/model.pkl
            echo "New model file moved to model/model.pkl."
          elif [ -f model/model.pkl ]; then
            echo "New model file already in model/model.pkl."
          else
            echo "New model file not found!"
            exit 1
          fi

      - name: Commit and Push New Model File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add model/model.pkl
          git commit -m "Retrained model: updated model.pkl" || echo "No changes detected."
          git push
