name: Retrain Model

# ① Give this workflow write permission so GITHUB_TOKEN can push commits
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (with write creds)
        uses: actions/checkout@v3
        with:
          # ② ensure the GITHUB_TOKEN is wired into git for pushes
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies Forcing NumPy < 2 + plotting libs
        run: |
          pip install --upgrade pip
          pip install numpy==1.24.3
          pip install seaborn matplotlib
          pip install -r app/requirements.txt
          python -c "import numpy, seaborn, matplotlib; \
                     print('NumPy:', numpy.__version__, \
                           'Seaborn:', seaborn.__version__, \
                           'Matplotlib:', matplotlib.__version__)"

      - name: List Resources Directory
        run: |
          echo "Listing contents of app/Resources and app/model:"
          ls -la app/Resources
          ls -la app/model || echo "app/model does not exist yet"

      - name: Remove Old Model File
        run: rm -f app/model/model.pkl

      - name: Retrain the Model
        working-directory: app
        run: python main.py retrain

      - name: Commit and Push New Model File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/model/model.pkl
          if ! git diff --cached --quiet; then
            git commit -m "Retrained model: update model.pkl"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
