name: Retrain Model

# ——————————————————————————————————————————————————————————————————————
# ① Give this workflow write permission so GITHUB_TOKEN can push commits
permissions:
  contents: write
# ——————————————————————————————————————————————————————————————————————

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (with full history & write creds)
        uses: actions/checkout@v3
        with:
          # ② fetch full history so we can rebase/merge
          fetch-depth: 0
          # ③ ensure the GITHUB_TOKEN is wired into git for pushes
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies Forcing NumPy < 2
        run: |
          pip install --upgrade pip
          pip install numpy==1.24.3
          pip install -r app/requirements.txt
          python -c "import numpy; print('NumPy version:', numpy.__version__)"

      - name: List Resources Directory
        run: |
          echo "Listing contents of app/Resources:"
          ls -la app/Resources

      - name: Remove Old Model File
        run: |
          rm -f app/model/model.pkl

      - name: Retrain the Model
        working-directory: app
        run: python main.py retrain

      - name: Move New Model File
        run: |
          if [ -f app/model.pkl ]; then
            mkdir -p app/model
            mv app/model.pkl app/model/model.pkl
          fi

      - name: Sync & Commit Updated model.pkl
        run: |
          # —————————————————————————————————————
          # ④ pull any remote changes before pushing (avoids non‑fast‑forward)
          git pull --rebase origin master
          # —————————————————————————————————————
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/model/model.pkl
          if ! git diff --cached --quiet; then
            git commit -m "Retrained model: update model.pkl"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
        env:
          # the built-in token is already available
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
