      # ⑤ Commit & push removal of the old model, then the new one
      - name: Commit removal & addition of model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"

          # 1️⃣ Make sure we're up to date
          git pull --rebase origin master

          # 2️⃣ If the old model exists in git, remove & commit it
          if git ls-files --error-unmatch app/model/model.pkl > /dev/null 2>&1; then
            git rm app/model/model.pkl
            git commit -m "Remove old model.pkl"
          fi

          # 3️⃣ Force‑add the newly generated model (bypass .gitignore if needed)
          git add -f app/model/model.pkl

          # 4️⃣ Commit only if it actually changed
          if ! git diff --cached --quiet; then
            git commit -m "Add retrained model.pkl"
            git push origin master
          else
            echo "No changes in model.pkl – nothing to push."
          fi
