name: Retrain Model

# ① Grant this workflow push rights to the repo
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # ② Checkout with the GITHUB_TOKEN wired into git
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # ③ Bring up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ④ Install your requirements, forcing numpy<2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install numpy==1.24.3
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f app/requirements.txt ]; then
            pip install -r app/requirements.txt
          fi
          # any extras your script needs
          pip install pandas scikit-learn seaborn matplotlib scipy joblib psycopg2 sqlalchemy

      # ⑤ Remove any old model
      - name: Remove Old Model File
        run: rm -f app/model/model.pkl

      # ⑥ Retrain (this writes app/model/model.pkl)
      - name: Retrain the Model
        run: python app/main.py retrain

      # ⑦ Debug: show that the file is really there
      - name: List New Model Directory
        run: |
          echo "Contents of app/model/:"
          ls -la app/model

      # ⑧ Commit & push if it changed
      - name: Commit & Push New Model File
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/model/model.pkl
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Retrained model: update model.pkl"
            git push origin HEAD:master
          else
            echo "✔ No changes in model.pkl to commit."
          fi
