name: Retrain Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          # Install your repository requirements.
          # Adjust the path below to match your repository structure.
          pip install -r requirements.txt || pip install -r app/requirements.txt
          # Explicitly install additional packages that your code uses.
          pip install numpy pandas scikit-learn seaborn matplotlib scipy joblib psycopg2 sqlalchemy

      - name: Remove Old Model File
        run: |
          if [ -f model/model.pkl ]; then
            echo "Removing old model model/model.pkl..."
            rm model/model.pkl
          else
            echo "No old model file found in model/ folder."
          fi

      - name: Retrain the Model
        run: |
          # Run main.py with the 'retrain' argument so it executes the training logic only.
          python app/main.py retrain

      - name: Move New Model File to model/ Folder
        run: |
          # If your training code writes the file as model.pkl in the repository root,
          # move it into the model directory.
          if [ -f model.pkl ]; then
            mkdir -p model
            mv model.pkl model/model.pkl
            echo "New model file moved to model/model.pkl."
          elif [ -f model/model.pkl ]; then
            echo "New model file already in model/model.pkl."
          else
            echo "New model file not found!"
            exit 1
          fi

      - name: Commit and Push New Model File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add model/model.pkl
          git commit -m "Retrained model: updated model.pkl" || echo "No changes detected."
          git push
