name: Retrain Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies Forcing NumPy < 2
        run: |
          pip install --upgrade pip
          # Install a specific version of NumPy that is compatible (here 1.24.3)
          pip install numpy==1.24.3
          # Install your requirements file (adjust the path if needed)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f app/requirements.txt ]; then
            pip install -r app/requirements.txt
          fi
          # Install additional packages needed by your code.
          pip install pandas scikit-learn seaborn matplotlib scipy joblib psycopg2 sqlalchemy
          # Reinstall numpy to ensure its version stays at 1.24.3
          pip install numpy==1.24.3 --force-reinstall
          python -c "import numpy; print('NumPy version:', numpy.__version__)"

      - name: List Resources Directory
        run: |
          echo "Listing contents of app/Resources:"
          ls -la app/Resources

      - name: Remove old model file
        run: rm -f app/model/model.pkl
        
      - name: Retrain the model
        working-directory: app
        run: python main.py retrain
      - name: Commit & push updated model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/model/model.pkl
          if ! git diff --cached --quiet; then
            git commit -m "Retrained model: update model.pkl"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
