name: Update Deployment Image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Image Tag in Deployment Manifest
        run: |
          echo "Updating deployment manifest with new image tag..."
          # This sed command finds any occurrence of the old image tag that matches:
          # us-central1-docker.pkg.dev/recoai-455707/ml-housing-repo/ml-housing-app:v1.0.<number>
          # and replaces it with the new static tag: v1.0.40
          sed -i "s|us-central1-docker.pkg.dev/recoai-455707/ml-housing-repo/ml-housing-app:v1\.0\.[0-9]*|us-central1-docker.pkg.dev/recoai-455707/ml-housing-repo/ml-housing-app:v1.0.40|g" manifests/deployment.yaml
          echo "Updated deployment manifest:"
          cat manifests/deployment.yaml

      - name: Commit and Push Updated Manifest
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          # Configure Git with a generic username and email
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # If there are changes in the manifest file, then commit and push them
          if [ -n "$(git status --porcelain manifests/deployment.yaml)" ]; then
              echo "Changes detected, committing and pushing..."
              git add manifests/deployment.yaml
              git commit -m "Update image tag to v1.0.40 in deployment manifest"
              # Set the remote URL explicitly with your username (fj405UOW) and the PAT.
              git remote set-url origin https://fj405UOW:${PUSH_TOKEN}@github.com/bmmahmud/gitops-ml-housing.git
              git push origin master
          else
              echo "No changes detected in the deployment manifest."
          fi
